# Generated by Django 2.2 on 2019-05-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20190510_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
