# Generated by Django 2.2 on 2019-05-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_auto_20190511_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
