# Generated by Django 2.2 on 2019-05-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0005_auto_20190511_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='relation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Relation'),
        ),
    ]
